<?php

namespace Lee\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * blogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class blogRepository extends EntityRepository
{
}
