<?php

namespace Lee\Bundle\Entity;

use Doctrine\ORM\EntityRepository;
use Lee\Bundle\Entity\user;

/**
 * userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userRepository extends EntityRepository
{
}
